### PR TITLE
feat : code changes for new serial part submodel with multi version and removed not supported maven modules 

### PR DESCRIPTION
**Pull request by ChetanT-System**
## Description
- Supported new serial part submodel with multi version support.
- Removed maven modules  serial-part-typization and assembly-part-relationship for update.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by almadigabor — DISMISSED** [review]

**Comment by ChetanT-System** [comment]
@almadigabor  I have updated changelog file and PR discription about removed maven modules.

**Comment by adityagajbhiye9** [comment]
@almadigabor Please review

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
