### PR TITLE
[feat|fix] : SDE backend : hot fix for 3.2 with pcf version

### PR DESCRIPTION
**Pull request by sachinargade123**
please close PR [#74](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/pull/74) this before this 
### Added
- Added oauth security for sde public api.
- BPN url add API path.

### Fixed
- Correct dataplane endpoint for digital twin.
- DSP endpoint path for digital-twin edc url.
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by adityagajbhiye9** [comment]
@FaGru3n Please merge this PR after #74 PR.

**Comment by FaGru3n** [comment]
@sachinargade123 could you please give me the information who is also in your team to validate the changes?

**Comment by adityagajbhiye9** [comment]
> @adityagajbhiye9 could you please raise a issue against us as to become a least a contributor to the Ecplise Tractus-X GitHub Organisation https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-add-project-contributor.md&title=New+Tractus-X+project+contributor

Sure, I will raise a issue.

**Comment by FaGru3n** [comment]
> > @adityagajbhiye9 could you please raise a issue against us as to become a least a contributor to the Ecplise Tractus-X GitHub Organisation https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-add-project-contributor.md&title=New+Tractus-X+project+contributor
> 
> Sure, I will raise a issue.

if i want to merge your PR ECA Check will fail, because you directly committed on @sachinargade123 branch... unless your a contributor to this project

please be also aware of 
https://eclipse-tractusx.github.io/docs/oss/how-to-contribute
https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by FaGru3n** [comment]
@dvasunin could you please verify the changes from @sachinargade123 and @adityagajbhiye9

**Comment by adityagajbhiye9** [comment]
@FaGru3n  I have raised issue.
https://github.com/eclipse-tractusx/sig-infra/issues/381

**Review by dvasunin — APPROVED** [review]
LGTM

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
@FaGru3n I have reviewed and approved.

**Comment by ChetanT-System** [comment]
@hzierer  Please review approve the PR
@FaGru3n Please merge merge the PR once approve ! 
Once merged this PR, We have to create one more PR(part_3) as part of PR split.

**Comment by FaGru3n** [comment]
> @hzierer Please review and approve the PR @FaGru3n Please merge merge the PR once approve ! Once merged this PR, We have to create one more PR(part_3) as part of PR split.

Hi @ChetanT-System thanks for mentioning, but why the pressure to me to merge? Only following our Tractus-X Release Guidlines and when there is no committer in your team, would be good if there were some member. That the upstream branch can updated regularly.

**Review by FaGru3n — APPROVED** [review]
LGTM - content can not verified structure of the PR seems good.

**Review by hzierer — APPROVED** [review]
Can't check the changes to java code. Rest LGTM

**Comment by ChetanT-System** [comment]
Hi @FaGru3n Thank you for your support !  I'm not pressuring to you :)

**Pull request merged**
