### PR TITLE
PCF exchange implementation update for 2408 release

### PR DESCRIPTION
**Pull request by sachinargade123**
## Description
-  PCF exchange changes for 2408 version.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by sachinargade123** [comment]
@amoldashwant @ChetanT-System @adityagajbhiye9 please review

**Review by amoldashwant — APPROVED** [review]
LGTM

**Review by amoldashwant — APPROVED** [review]
LGTM

**Review by ChetanT-System — APPROVED** [review]
Looks good to me.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
