### PR TITLE
doc | Added new flyway  missing files

### PR DESCRIPTION
**Pull request by ChetanT-System**
## Description
- Added new flyway files

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ChetanT-System** [comment]
@sachinargade123 , @amoldashwant  Please review and approve the PR.

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Comment by sachinargade123** [comment]
@amoldashwant please review and approve the PR.

**Review by amoldashwant — APPROVED** [review]
Changes look good to me

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
