### PR TITLE
[feat|sde-backend] : dt provider configuration

### PR DESCRIPTION
**Pull request by ChetanT-System**
### Added
- Added DT asset provider configuration on start up.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Review by dvasunin — APPROVED** [review]
LGTM

**Review by almadigabor — CHANGES_REQUESTED** [review]
Please fix the license headers in the PRs files either:

- by removing the second year and only keeping the creation year.
- by adjusting the second year (last modified) to 2024

**Comment by ChetanT-System** [comment]
@almadigabor - Updated copyright hearders

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
