### PR TITLE
feat | Release edc 7 support

### PR DESCRIPTION
**Pull request by sachinargade123**
### Added
- implmentation of EDC 7 support

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Review by almadigabor — CHANGES_REQUESTED** [review]
There are multiple problems with license header formats and dates. Please check and fix all files in the PR. You can find a guideline [here](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header).

**Review by almadigabor — CHANGES_REQUESTED** [review]
The license header format is still wrong, there is no space after the comma. Should be like e.g.: 2021,2024. See my previous comment for guidance.

**Review by adityagajbhiye9 — APPROVED** [review]
Changes look good to me.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
