### PR TITLE
[fix|sde-backend] : Fix Open api doc for KICS

### PR DESCRIPTION
**Pull request by sachinargade123**
### Fixed
- Open API docs update for kics fix
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by adityagajbhiye9** [comment]
@amoldashwant Please review and approve

**Review by dvasunin — APPROVED** [review]
While I am approving it, are you sure 3 is enough for an array? I usually use a big number in similar situation, e.g. 512 or higher.

**Review by adityagajbhiye9 — APPROVED** [review]
LGTM

**Comment by sachinargade123** [comment]
Closing this PR. The suggested changes are available with #100

**Pull request closed without merging**
