### PR TITLE
fix | rename edc_request_template directory

### PR DESCRIPTION
**Pull request by sachinargade123**
## Description

- Rename edc_request_template directory
- This is fixed for #147

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by sachinargade123** [comment]
@amoldashwant please review this PR.

**Comment by amoldashwant** [comment]
Change looks good to me.

**Review by adkumar1 — APPROVED** [review]
Looks good

**Review by amoldashwant — APPROVED** [review]
Fix looks good to me.

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
