### PR TITLE
[SDE backend-2.0.1] Merging code to master branch for automatic identification of submodel for processing.

### PR DESCRIPTION
**Pull request by adityagajbhiye9**
- Add automatic identification of submodel for processing.

### CODE REVIEW

**Review by sachinargade123 — APPROVED** [review]
Changes look ok for me

**Review by almadigabor — COMMENTED** [review]
Looks good to me. Are there any new dependencies or dependency versions introduced? I see one new import in one of the java files. If yes, please also run the dash tool according to the [guide](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04).

**Comment by adityagajbhiye9** [comment]
Checking java files and will re-run dash tool.

**Comment by almadigabor** [comment]
Ok. Approved and merged.

**Pull request merged**
