### PR TITLE
feat | refactor code for correction semantic id in pcf submodel

### PR DESCRIPTION
**Pull request by ChetanT-System**
## Description
- Correction in semanticId changes in pcf.
- Fix for PCF data sovereignty test

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by ChetanT-System** [comment]
@sachinargade123 , @amoldashwant  Please review and approve the PR.

**Review by sachinargade123 — APPROVED** [review]
LGTM

**Comment by adityagajbhiye9** [comment]
@amoldashwant  Please review and approve

**Review by amoldashwant — APPROVED** [review]
LGTM

**Review by almadigabor — CHANGES_REQUESTED** [review]
Please fix the license headers in all of the files in the PR. For example don't put whitespaces between the years. You can see the rules [here](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02/#copyright-and-license-header).

**Comment by adityagajbhiye9** [comment]
@ChetanT-System  Please check.

**Comment by ChetanT-System** [comment]
> Please fix the license headers in all of the files in the PR. For example don't put whitespaces between the years. You can see the rules [here](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02/#copyright-and-license-header).

Corrected license headers. Please review again and approve

**Review by almadigabor — APPROVED** [review]

**Pull request merged**
